spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: xxx
            client-secret: xxx

  webflux:
    hiddenmethod:
      filter:
        enabled: true
